DROP SEQUENCE CTX_ID;
DROP TABLE Contexto_TAB;
DROP TYPE Contexto_TYP;
DROP TABLE CatalogoCtx_TAB;
DROP TABLE ContextoDim_TAB;
DROP TABLE DomDimensionCtx_TAB;
DROP TYPE ListaDomDimensionCtx_TYP;
DROP TYPE DomDimensionCtx_TYP;
DROP TABLE DependenciaCtx_TAB;
DROP TABLE DimensionCtx_TAB;
DROP TABLE UsuarioCtx_TAB;

DROP TABLE JPE_TAB;
DROP TABLE MEDICO;
DROP TABLE PACIENTE;
DROP TYPE DomPeso;