SET LINESIZE 100
SET PAGESIZE 200
SET HEADING OFF
SET SERVEROUTPUT ON

SELECT * FROM DOMINIODIFUSO_TAB;
-------------------------------------------
SELECT * FROM USUARIOCTX_TAB;
-------------------------------------------
SELECT * FROM DIMENSIONCTX_TAB;

SELECT D.DOMINIO.NOMBRE, D.DIMENSION.NOMBRE 
FROM DEPENDENCIACTX_TAB D;

SELECT D.USUARIO.NOMBRE, D.DIMENSION.DIMENSION.NOMBRE, D.DIMENSION.DOMINIO
FROM DOMDIMENSIONCTX_TAB D;
-------------------------------------------
SELECT * FROM CATALOGOCTX_TAB;
-------------------------------------------
SELECT * FROM JPE_TAB;