--conn system/19254844;
--Eliminacion de todos los TYPES en la BD

DROP TYPE UserDef_objtyp FORCE;
DROP TYPE Fuzzy_objtyp FORCE;
DROP TYPE Trapezoid_objtyp FORCE;
DROP TYPE DT_objtyp FORCE;
DROP TYPE D_Peso FORCE;
DROP TYPE semejanza_etiquetas_t;
DROP TYPE dispositivos_usados_t;
DROP TYPE semejanza_fijo_etiqueta_t;
DROP TYPE etiqueta_t;
DROP TYPE dominio_fijo_t;
DROP TYPE dominio_t;
DROP TYPE Paciente_t;
DROP TYPE Medico_t;

DROP TYPE D_TALLA;
DROP TYPE D_CAD_1;
DROP TYPE D_FLEXCAD;
DROP TYPE D_EXTCAD;
DROP TYPE D_ABD0;
DROP TYPE D_ABD9;
DROP TYPE D_ABD;
DROP TYPE D_ANTFEM;
DROP TYPE D_ROTINT;
DROP TYPE D_ROTEXT;
DROP TYPE D_EJEBIM;
DROP TYPE D_ANGPIE;
DROP TYPE D_FLEXROD;
DROP TYPE D_SLR;
DROP TYPE D_DORROD9;
DROP TYPE D_DORROD0;
DROP TYPE D_PLANFLEX;
DROP TYPE D_INVER;
DROP TYPE D_EVER;
DROP TYPE DOMINIO_FIJO_T2;
DROP TYPE ETIQUETA_T2;
