/*
	CAA_Definicion
	
	Definición de estructuras sobre dominios difusos.
	
	Ramón Marquez
	Esteban Oliveros
	Arturo Voltattorni

*/

-- DEFINICION DE DOMINIOS CONTINUOS

CREATE OR REPLACE TYPE  D_Peso UNDER Continuo_TYP (
   CONSTRUCTOR FUNCTION D_Peso (Lab IN VARCHAR2, N1 IN NUMBER, N2 IN NUMBER, N3 IN NUMBER, N4 IN NUMBER) RETURN SELF AS RESULT,
   CONSTRUCTOR FUNCTION D_Peso (Lab IN VARCHAR2) RETURN SELF AS RESULT,
   CONSTRUCTOR FUNCTION D_Peso (Num IN NUMBER) RETURN SELF AS RESULT,
   MEMBER FUNCTION LSHOW RETURN VARCHAR2,
   MEMBER FUNCTION FEQ (L1 IN VARCHAR2) RETURN REAL   
);
/

CREATE OR REPLACE TYPE  D_Talla UNDER Continuo_TYP (
   CONSTRUCTOR FUNCTION D_Talla (Lab IN VARCHAR2, N1 IN NUMBER, N2 IN NUMBER, N3 IN NUMBER, N4 IN NUMBER) RETURN SELF AS RESULT,
   CONSTRUCTOR FUNCTION D_Talla (Lab IN VARCHAR2) RETURN SELF AS RESULT,
   CONSTRUCTOR FUNCTION D_Talla (Num IN NUMBER) RETURN SELF AS RESULT,
   MEMBER FUNCTION LSHOW RETURN VARCHAR2,
   MEMBER FUNCTION FEQ (L1 IN VARCHAR2) RETURN REAL   
);
/

CREATE OR REPLACE TYPE  D_cad_1 UNDER Continuo_TYP (
   CONSTRUCTOR FUNCTION D_cad_1 (Lab IN VARCHAR2, N1 IN NUMBER, N2 IN NUMBER, N3 IN NUMBER, N4 IN NUMBER) RETURN SELF AS RESULT,
   CONSTRUCTOR FUNCTION D_cad_1 (Lab IN VARCHAR2) RETURN SELF AS RESULT,
   CONSTRUCTOR FUNCTION D_cad_1 (Num IN NUMBER) RETURN SELF AS RESULT,
   MEMBER FUNCTION LSHOW RETURN VARCHAR2,
   MEMBER FUNCTION FEQ (L1 IN VARCHAR2) RETURN REAL   
);
/

CREATE OR REPLACE TYPE  D_FlexCad UNDER Continuo_TYP (
   CONSTRUCTOR FUNCTION D_FlexCad (Lab IN VARCHAR2, N1 IN NUMBER, N2 IN NUMBER, N3 IN NUMBER, N4 IN NUMBER) RETURN SELF AS RESULT,
   CONSTRUCTOR FUNCTION D_FlexCad (Lab IN VARCHAR2) RETURN SELF AS RESULT,
   CONSTRUCTOR FUNCTION D_FlexCad (Num IN NUMBER) RETURN SELF AS RESULT,
   MEMBER FUNCTION LSHOW RETURN VARCHAR2,
   MEMBER FUNCTION FEQ (L1 IN VARCHAR2) RETURN REAL   
);
/

CREATE OR REPLACE TYPE  D_ExtCad UNDER Continuo_TYP (
   CONSTRUCTOR FUNCTION D_ExtCad (Lab IN VARCHAR2, N1 IN NUMBER, N2 IN NUMBER, N3 IN NUMBER, N4 IN NUMBER) RETURN SELF AS RESULT,
   CONSTRUCTOR FUNCTION D_ExtCad (Lab IN VARCHAR2) RETURN SELF AS RESULT,
   CONSTRUCTOR FUNCTION D_ExtCad (Num IN NUMBER) RETURN SELF AS RESULT,
   MEMBER FUNCTION LSHOW RETURN VARCHAR2,
   MEMBER FUNCTION FEQ (L1 IN VARCHAR2) RETURN REAL   
);
/

CREATE OR REPLACE TYPE  D_Abd0 UNDER Continuo_TYP (
   CONSTRUCTOR FUNCTION D_Abd0 (Lab IN VARCHAR2, N1 IN NUMBER, N2 IN NUMBER, N3 IN NUMBER, N4 IN NUMBER) RETURN SELF AS RESULT,
   CONSTRUCTOR FUNCTION D_Abd0 (Lab IN VARCHAR2) RETURN SELF AS RESULT,
   CONSTRUCTOR FUNCTION D_Abd0 (Num IN NUMBER) RETURN SELF AS RESULT,
   MEMBER FUNCTION LSHOW RETURN VARCHAR2,
   MEMBER FUNCTION FEQ (L1 IN VARCHAR2) RETURN REAL   
);
/

CREATE OR REPLACE TYPE  D_Abd9 UNDER Continuo_TYP (
   CONSTRUCTOR FUNCTION D_Abd9 (Lab IN VARCHAR2, N1 IN NUMBER, N2 IN NUMBER, N3 IN NUMBER, N4 IN NUMBER) RETURN SELF AS RESULT,
   CONSTRUCTOR FUNCTION D_Abd9 (Lab IN VARCHAR2) RETURN SELF AS RESULT,
   CONSTRUCTOR FUNCTION D_Abd9 (Num IN NUMBER) RETURN SELF AS RESULT,
   MEMBER FUNCTION LSHOW RETURN VARCHAR2,
   MEMBER FUNCTION FEQ (L1 IN VARCHAR2) RETURN REAL   
);
/

CREATE OR REPLACE TYPE  D_Abd UNDER Continuo_TYP (
   CONSTRUCTOR FUNCTION D_Abd (Lab IN VARCHAR2, N1 IN NUMBER, N2 IN NUMBER, N3 IN NUMBER, N4 IN NUMBER) RETURN SELF AS RESULT,
   CONSTRUCTOR FUNCTION D_Abd (Lab IN VARCHAR2) RETURN SELF AS RESULT,
   CONSTRUCTOR FUNCTION D_Abd (Num IN NUMBER) RETURN SELF AS RESULT,
   MEMBER FUNCTION LSHOW RETURN VARCHAR2,
   MEMBER FUNCTION FEQ (L1 IN VARCHAR2) RETURN REAL   
);
/

CREATE OR REPLACE TYPE  D_AntFem UNDER Continuo_TYP (
   CONSTRUCTOR FUNCTION D_AntFem (Lab IN VARCHAR2, N1 IN NUMBER, N2 IN NUMBER, N3 IN NUMBER, N4 IN NUMBER) RETURN SELF AS RESULT,
   CONSTRUCTOR FUNCTION D_AntFem (Lab IN VARCHAR2) RETURN SELF AS RESULT,
   CONSTRUCTOR FUNCTION D_AntFem (Num IN NUMBER) RETURN SELF AS RESULT,
   MEMBER FUNCTION LSHOW RETURN VARCHAR2,
   MEMBER FUNCTION FEQ (L1 IN VARCHAR2) RETURN REAL   
);
/

CREATE OR REPLACE TYPE  D_RotInt UNDER Continuo_TYP (
   CONSTRUCTOR FUNCTION D_RotInt (Lab IN VARCHAR2, N1 IN NUMBER, N2 IN NUMBER, N3 IN NUMBER, N4 IN NUMBER) RETURN SELF AS RESULT,
   CONSTRUCTOR FUNCTION D_RotInt (Lab IN VARCHAR2) RETURN SELF AS RESULT,
   CONSTRUCTOR FUNCTION D_RotInt (Num IN NUMBER) RETURN SELF AS RESULT,
   MEMBER FUNCTION LSHOW RETURN VARCHAR2,
   MEMBER FUNCTION FEQ (L1 IN VARCHAR2) RETURN REAL   
);
/

CREATE OR REPLACE TYPE  D_RotExt UNDER Continuo_TYP (
   CONSTRUCTOR FUNCTION D_RotExt (Lab IN VARCHAR2, N1 IN NUMBER, N2 IN NUMBER, N3 IN NUMBER, N4 IN NUMBER) RETURN SELF AS RESULT,
   CONSTRUCTOR FUNCTION D_RotExt (Lab IN VARCHAR2) RETURN SELF AS RESULT,
   CONSTRUCTOR FUNCTION D_RotExt (Num IN NUMBER) RETURN SELF AS RESULT,
   MEMBER FUNCTION LSHOW RETURN VARCHAR2,
   MEMBER FUNCTION FEQ (L1 IN VARCHAR2) RETURN REAL   
);
/

CREATE OR REPLACE TYPE  D_EjeBim UNDER Continuo_TYP (
   CONSTRUCTOR FUNCTION D_EjeBim (Lab IN VARCHAR2, N1 IN NUMBER, N2 IN NUMBER, N3 IN NUMBER, N4 IN NUMBER) RETURN SELF AS RESULT,
   CONSTRUCTOR FUNCTION D_EjeBim (Lab IN VARCHAR2) RETURN SELF AS RESULT,
   CONSTRUCTOR FUNCTION D_EjeBim (Num IN NUMBER) RETURN SELF AS RESULT,
   MEMBER FUNCTION LSHOW RETURN VARCHAR2,
   MEMBER FUNCTION FEQ (L1 IN VARCHAR2) RETURN REAL   
);
/

CREATE OR REPLACE TYPE  D_AngPie UNDER Continuo_TYP (
   CONSTRUCTOR FUNCTION D_AngPie (Lab IN VARCHAR2, N1 IN NUMBER, N2 IN NUMBER, N3 IN NUMBER, N4 IN NUMBER) RETURN SELF AS RESULT,
   CONSTRUCTOR FUNCTION D_AngPie (Lab IN VARCHAR2) RETURN SELF AS RESULT,
   CONSTRUCTOR FUNCTION D_AngPie (Num IN NUMBER) RETURN SELF AS RESULT,
   MEMBER FUNCTION LSHOW RETURN VARCHAR2,
   MEMBER FUNCTION FEQ (L1 IN VARCHAR2) RETURN REAL   
);
/

CREATE OR REPLACE TYPE  D_FlexRod UNDER Continuo_TYP (
   CONSTRUCTOR FUNCTION D_FlexRod (Lab IN VARCHAR2, N1 IN NUMBER, N2 IN NUMBER, N3 IN NUMBER, N4 IN NUMBER) RETURN SELF AS RESULT,
   CONSTRUCTOR FUNCTION D_FlexRod (Lab IN VARCHAR2) RETURN SELF AS RESULT,
   CONSTRUCTOR FUNCTION D_FlexRod (Num IN NUMBER) RETURN SELF AS RESULT,
   MEMBER FUNCTION LSHOW RETURN VARCHAR2,
   MEMBER FUNCTION FEQ (L1 IN VARCHAR2) RETURN REAL   
);
/

CREATE OR REPLACE TYPE  D_Slr UNDER Continuo_TYP (
   CONSTRUCTOR FUNCTION D_Slr (Lab IN VARCHAR2, N1 IN NUMBER, N2 IN NUMBER, N3 IN NUMBER, N4 IN NUMBER) RETURN SELF AS RESULT,
   CONSTRUCTOR FUNCTION D_Slr (Lab IN VARCHAR2) RETURN SELF AS RESULT,
   CONSTRUCTOR FUNCTION D_Slr (Num IN NUMBER) RETURN SELF AS RESULT,
   MEMBER FUNCTION LSHOW RETURN VARCHAR2,
   MEMBER FUNCTION FEQ (L1 IN VARCHAR2) RETURN REAL   
);
/

CREATE OR REPLACE TYPE  D_DorRod9 UNDER Continuo_TYP (
   CONSTRUCTOR FUNCTION D_DorRod9 (Lab IN VARCHAR2, N1 IN NUMBER, N2 IN NUMBER, N3 IN NUMBER, N4 IN NUMBER) RETURN SELF AS RESULT,
   CONSTRUCTOR FUNCTION D_DorRod9 (Lab IN VARCHAR2) RETURN SELF AS RESULT,
   CONSTRUCTOR FUNCTION D_DorRod9 (Num IN NUMBER) RETURN SELF AS RESULT,
   MEMBER FUNCTION LSHOW RETURN VARCHAR2,
   MEMBER FUNCTION FEQ (L1 IN VARCHAR2) RETURN REAL   
);
/

CREATE OR REPLACE TYPE  D_DorRod0 UNDER Continuo_TYP (
   CONSTRUCTOR FUNCTION D_DorRod0 (Lab IN VARCHAR2, N1 IN NUMBER, N2 IN NUMBER, N3 IN NUMBER, N4 IN NUMBER) RETURN SELF AS RESULT,
   CONSTRUCTOR FUNCTION D_DorRod0 (Lab IN VARCHAR2) RETURN SELF AS RESULT,
   CONSTRUCTOR FUNCTION D_DorRod0 (Num IN NUMBER) RETURN SELF AS RESULT,
   MEMBER FUNCTION LSHOW RETURN VARCHAR2,
   MEMBER FUNCTION FEQ (L1 IN VARCHAR2) RETURN REAL   
);
/

CREATE OR REPLACE TYPE  D_PlanFlex UNDER Continuo_TYP (
   CONSTRUCTOR FUNCTION D_PlanFlex (Lab IN VARCHAR2, N1 IN NUMBER, N2 IN NUMBER, N3 IN NUMBER, N4 IN NUMBER) RETURN SELF AS RESULT,
   CONSTRUCTOR FUNCTION D_PlanFlex (Lab IN VARCHAR2) RETURN SELF AS RESULT,
   CONSTRUCTOR FUNCTION D_PlanFlex (Num IN NUMBER) RETURN SELF AS RESULT,
   MEMBER FUNCTION LSHOW RETURN VARCHAR2,
   MEMBER FUNCTION FEQ (L1 IN VARCHAR2) RETURN REAL   
);
/

CREATE OR REPLACE TYPE  D_Inver UNDER Continuo_TYP (
   CONSTRUCTOR FUNCTION D_Inver (Lab IN VARCHAR2, N1 IN NUMBER, N2 IN NUMBER, N3 IN NUMBER, N4 IN NUMBER) RETURN SELF AS RESULT,
   CONSTRUCTOR FUNCTION D_Inver (Lab IN VARCHAR2) RETURN SELF AS RESULT,
   CONSTRUCTOR FUNCTION D_Inver (Num IN NUMBER) RETURN SELF AS RESULT,
   MEMBER FUNCTION LSHOW RETURN VARCHAR2,
   MEMBER FUNCTION FEQ (L1 IN VARCHAR2) RETURN REAL   
);
/

CREATE OR REPLACE TYPE  D_Ever UNDER Continuo_TYP (
   CONSTRUCTOR FUNCTION D_Ever (Lab IN VARCHAR2, N1 IN NUMBER, N2 IN NUMBER, N3 IN NUMBER, N4 IN NUMBER) RETURN SELF AS RESULT,
   CONSTRUCTOR FUNCTION D_Ever (Lab IN VARCHAR2) RETURN SELF AS RESULT,
   CONSTRUCTOR FUNCTION D_Ever (Num IN NUMBER) RETURN SELF AS RESULT,
   MEMBER FUNCTION LSHOW RETURN VARCHAR2,
   MEMBER FUNCTION FEQ (L1 IN VARCHAR2) RETURN REAL   
);
/